export const textos = {
  email: "E-mail",
  senha: "Senha",
  entrar: "Entrar",
  cadastrar: "Cadastrar",
  recuperar: "Recuperar senha",
  nome: "Nome",
  inserir: "Inserir Foto",
  senhaconfirmar: "Confirmar senha",
  whatsapp: "WhatsApp",
  perfil: "Perfil",
  definirhorario: "Definir Horário",
  confirmarvaga: "Confirmar vaga",
  cancelar: "Cancelar",
  juntando: "Juntando",
  juntandodesc:
    "Você já fez a sua parte! Aguarde outro passageiro entrar no grupo.",
  juntandoMessage:
    "Mandaremos mensagem no seu whatsapp quando outro passageiro entrar nesse grupo.",
  quase: "Quase lá...",
  quaseMessage:
    "Agora só falta um motorista aceitar a corrida para confirmar a viagem!",
  motoristaconfirmado: "Motorista confirmado",
  finished: "Viagem Finalizada!",
  chegou: "Você chegou mais rápido e economizou!",
  pague: "Pague o seu motorista",
  agendar: "Agendar volta",
  alterarprofile: "Alterar",
  loggout: "Sair",
  adicionar: "Adicionar Imagem",
  alterar: "Alterar Imagem",
  embarque: "Embarque",
  desembarque: "Desembarque",
  gps: "gps",
  finalizar: "Finalizar",
  parabens: "Parabéns",
  corrida: "Corrida finalizada com sucesso!",
  fazermais: "Fazer mais corridas",
  finance: "Financeiro",
  today: "Hoje",
};
